services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - 5678:5678
    environment:
      GENERIC_TIMEZONE: "Asia/Kuala_Lumpur"
      TZ: "Asia/Kuala_Lumpur"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
      N8N_RUNNERS_ENABLED: true
    volumes:
      - n8n-data:/home/node/.n8n

volumes:
  - n8n-data:
