volumes:
  open-webui:

services:
  open-webui-cpu:
    image: ghcr.io/open-webui/open-webui:main # stable
    # other variant images
    # image: ghcr.io/open-webui/open-webui:main-slim # slim stable
    # image: ghcr.io/open-webui/open-webui:dev # development
    # image: ghcr.io/open-webui/open-webui:dev-slim # slim development
    restart: always
    ports:
      - 3000:8080
    extra_hosts:
      host.docker.internal: host-gateway
    volumes:
      - open-webui:/app/backend/data
